### ISSUE TITLE
MacOS + python3.8

### ISSUE THREAD

**Issue by ppussar** [cyraxjoe/awake#4]
After upgrading python to v3.8, awake does not run anymore:
zsh: /usr/local/bin/awake: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory

`pip install --upgrade awake`

does not solve the problem.

**Comment by cyraxjoe** [comment]
@ppussar  I think that the problem is that with `pip` the scripts are bound to the interpreter that installed the package by adding a shebang at the top.

Maybe something like will do the trick (forcing the reinstall with the new pip bound to the new python version):

`pip install --upgrade --force-reinstall awake`

**Comment by ppussar** [comment]
@cyraxjoe Thanks for the hint, unfortunately it doesn't solve my issue

```
$ pip install --upgrade --force-reinstall awake
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Processing /Users/ppussar/Library/Caches/pip/wheels/a7/c8/54/36859e4f51330b2bc67b5f8450f7452392b96c017bb76daac2/awake-1.0-py2-none-any.whl
Installing collected packages: awake
  Attempting uninstall: awake
    Found existing installation: awake 1.0
    Uninstalling awake-1.0:
      Successfully uninstalled awake-1.0
Successfully installed awake-1.0
$ awake
zsh: /usr/local/bin/awake: bad interpreter: /usr/local/opt/python/bin/python3.7: no such file or directory
```

**Comment by cyraxjoe** [comment]
:thinking:  @ppussar  could you run `head -n 1 $(which awake)`

**Comment by ppussar** [comment]
```
head -n 1 $(which awake)
#!/usr/local/opt/python/bin/python3.7

**Comment by cyraxjoe** [comment]
Interesting... can you do the same for pip `head -n 1 $(which pip)`, somehow `pip` is configuring a bad interpreter in the script.

**Comment by ppussar** [comment]
```
head -n 1 $(which pip)
#!/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python

**Comment by cyraxjoe** [comment]
Are you using `brew` to install python? Maybe this question is relevant to your situation https://stackoverflow.com/questions/31768128/pip-installation-usr-local-opt-python-bin-python2-7-bad-interpreter-no-such-f

**Comment by ppussar** [comment]
Yes indeed, I installed it with brew. On the linked paged I noticed the pip3 command. Trying `pip3 install --upgrade --force-reinstall awake` fixed the issue for me :) 
Thanks for your support @cyraxjoe
